package com.survey.entity;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CompanyUser generated by hbm2java
 */
@Entity
@Table(name="companyUser"
    ,schema="dbo"
    ,catalog="onlineSurvey"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cu_email"), @UniqueConstraint(columnNames="cu_phone")} 
)
public class CompanyUser  implements java.io.Serializable {


     private String cuName;
     private Company company;
     private String cuPhoto;
     private String cuPhone;
     private String cuEmail;
     private String cuPassword;
     private String cuSex;
     private String cuDateOfBirth;
     private String cuHobby;
     private Set<Survey> surveys = new HashSet(0);

    public CompanyUser() {
    }

	
    public CompanyUser(String cuName) {
        this.cuName = cuName;
    }
    public CompanyUser(String cuName, Company company, String cuPhoto, String cuPhone, String cuEmail, String cuPassword, String cuSex, String cuDateOfBirth, String cuHobby, Set surveys) {
       this.cuName = cuName;
       this.company = company;
       this.cuPhoto = cuPhoto;
       this.cuPhone = cuPhone;
       this.cuEmail = cuEmail;
       this.cuPassword = cuPassword;
       this.cuSex = cuSex;
       this.cuDateOfBirth = cuDateOfBirth;
       this.cuHobby = cuHobby;
       this.surveys = surveys;
    }
   
     @Id 

    
    @Column(name="cu_name", unique=true, nullable=false, length=10)
    public String getCuName() {
        return this.cuName;
    }
    
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

@ManyToOne(fetch=FetchType.LAZY,targetEntity=Company.class)
    @JoinColumn(name="companyName")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="cu_photo", length=300)
    public String getCuPhoto() {
        return this.cuPhoto;
    }
    
    public void setCuPhoto(String cuPhoto) {
        this.cuPhoto = cuPhoto;
    }

    
    @Column(name="cu_phone", unique=true, length=20)
    public String getCuPhone() {
        return this.cuPhone;
    }
    
    public void setCuPhone(String cuPhone) {
        this.cuPhone = cuPhone;
    }

    
    @Column(name="cu_email", unique=true, length=30)
    public String getCuEmail() {
        return this.cuEmail;
    }
    
    public void setCuEmail(String cuEmail) {
        this.cuEmail = cuEmail;
    }

    
    @Column(name="cu_password", length=20)
    public String getCuPassword() {
        return this.cuPassword;
    }
    
    public void setCuPassword(String cuPassword) {
        this.cuPassword = cuPassword;
    }

    
    @Column(name="cu_sex", length=5)
    public String getCuSex() {
        return this.cuSex;
    }
    
    public void setCuSex(String cuSex) {
        this.cuSex = cuSex;
    }

    
    @Column(name="cu_dateOfBirth", length=50)
    public String getCuDateOfBirth() {
        return this.cuDateOfBirth;
    }
    
    public void setCuDateOfBirth(String cuDateOfBirth) {
        this.cuDateOfBirth = cuDateOfBirth;
    }

    
    @Column(name="cu_hobby", length=50)
    public String getCuHobby() {
        return this.cuHobby;
    }
    
    public void setCuHobby(String cuHobby) {
        this.cuHobby = cuHobby;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyUser",targetEntity=Survey.class)
    public Set getSurveys() {
        return this.surveys;
    }
    
    public void setSurveys(Set surveys) {
        this.surveys = surveys;
    }




}


