package com.survey.entity;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name="manager"
    ,schema="dbo"
    ,catalog="onlineSurvey"
)
public class Manager  implements java.io.Serializable {


     private String MId;
     private String MPassword;

    public Manager() {
    }

	
    public Manager(String MId) {
        this.MId = MId;
    }
    public Manager(String MId, String MPassword) {
       this.MId = MId;
       this.MPassword = MPassword;
    }
   
     @Id 

    
    @Column(name="m_id", unique=true, nullable=false, length=10)
    public String getMId() {
        return this.MId;
    }
    
    public void setMId(String MId) {
        this.MId = MId;
    }

    
    @Column(name="m_password", length=20)
    public String getMPassword() {
        return this.MPassword;
    }
    
    public void setMPassword(String MPassword) {
        this.MPassword = MPassword;
    }




}


