package com.survey.entity;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrdinaryUser generated by hbm2java
 */
@Entity
@Table(name="ordinaryUser"
    ,schema="dbo"
    ,catalog="onlineSurvey"
    , uniqueConstraints = {@UniqueConstraint(columnNames="ou_email"), @UniqueConstraint(columnNames="ou_phone")} 
)
public class OrdinaryUser  implements java.io.Serializable {


     private String ouName;
     private String ouPhoto;
     private String ouPhone;
     private String ouEmail;
     private String ouPassword;
     private String ouSex;
     private String ouDateOfBirth;
     private String ouHobby;
     private Set<UserAnswer> userAnswers = new HashSet(0);

    public OrdinaryUser() {
    }

	
    public OrdinaryUser(String ouName) {
        this.ouName = ouName;
    }
    public OrdinaryUser(String ouName, String ouPhoto, String ouPhone, String ouEmail, String ouPassword, String ouSex, String ouDateOfBirth, String ouHobby, Set userAnswers) {
       this.ouName = ouName;
       this.ouPhoto = ouPhoto;
       this.ouPhone = ouPhone;
       this.ouEmail = ouEmail;
       this.ouPassword = ouPassword;
       this.ouSex = ouSex;
       this.ouDateOfBirth = ouDateOfBirth;
       this.ouHobby = ouHobby;
       this.userAnswers = userAnswers;
    }
   
     @Id 

    
    @Column(name="ou_name", unique=true, nullable=false, length=10)
    public String getOuName() {
        return this.ouName;
    }
    
    public void setOuName(String ouName) {
        this.ouName = ouName;
    }

    
    @Column(name="ou_photo", length=300)
    public String getOuPhoto() {
        return this.ouPhoto;
    }
    
    public void setOuPhoto(String ouPhoto) {
        this.ouPhoto = ouPhoto;
    }

    
    @Column(name="ou_phone", unique=true, length=20)
    public String getOuPhone() {
        return this.ouPhone;
    }
    
    public void setOuPhone(String ouPhone) {
        this.ouPhone = ouPhone;
    }

    
    @Column(name="ou_email", unique=true, length=30)
    public String getOuEmail() {
        return this.ouEmail;
    }
    
    public void setOuEmail(String ouEmail) {
        this.ouEmail = ouEmail;
    }

    
    @Column(name="ou_password", length=20)
    public String getOuPassword() {
        return this.ouPassword;
    }
    
    public void setOuPassword(String ouPassword) {
        this.ouPassword = ouPassword;
    }

    
    @Column(name="ou_sex", length=5)
    public String getOuSex() {
        return this.ouSex;
    }
    
    public void setOuSex(String ouSex) {
        this.ouSex = ouSex;
    }

    
    @Column(name="ou_dateOfBirth", length=50)
    public String getOuDateOfBirth() {
        return this.ouDateOfBirth;
    }
    
    public void setOuDateOfBirth(String ouDateOfBirth) {
        this.ouDateOfBirth = ouDateOfBirth;
    }

    
    @Column(name="ou_hobby", length=50)
    public String getOuHobby() {
        return this.ouHobby;
    }
    
    public void setOuHobby(String ouHobby) {
        this.ouHobby = ouHobby;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="ordinaryUser",targetEntity=UserAnswer.class)
    public Set getUserAnswers() {
        return this.userAnswers;
    }
    
    public void setUserAnswers(Set userAnswers) {
        this.userAnswers = userAnswers;
    }




}


