package com.survey.entity;



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name="question"
    ,schema="dbo"
    ,catalog="onlineSurvey"
)
public class Question  implements java.io.Serializable {


     private QuestionId id;
     private Survey survey;
     private String QContent;
     private String aoption;
     private String boption;
     private String coption;
     private String doption;
     private String eoption;
     private String foption;
     private String QType;
     private Integer QSize;

    public Question() {
    }

	
    public Question(QuestionId id, Survey survey) {
        this.id = id;
        this.survey = survey;
    }
    public Question(QuestionId id, Survey survey, String QContent, String aoption, String boption, String coption, String doption, String eoption, String foption, String QType, Integer QSize) {
       this.id = id;
       this.survey = survey;
       this.QContent = QContent;
       this.aoption = aoption;
       this.boption = boption;
       this.coption = coption;
       this.doption = doption;
       this.eoption = eoption;
       this.foption = foption;
       this.QType = QType;
       this.QSize = QSize;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="SId", column=@Column(name="s_id", nullable=false) ), 
        @AttributeOverride(name="QId", column=@Column(name="q_id", nullable=false) ) } )
    public QuestionId getId() {
        return this.id;
    }
    
    public void setId(QuestionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="s_id", nullable=false, insertable=false, updatable=false)
    public Survey getSurvey() {
        return this.survey;
    }
    
    public void setSurvey(Survey survey) {
        this.survey = survey;
    }

    
    @Column(name="q_content", length=100)
    public String getQContent() {
        return this.QContent;
    }
    
    public void setQContent(String QContent) {
        this.QContent = QContent;
    }

    
    @Column(name="Aoption", length=100)
    public String getAoption() {
        return this.aoption;
    }
    
    public void setAoption(String aoption) {
        this.aoption = aoption;
    }

    
    @Column(name="Boption", length=100)
    public String getBoption() {
        return this.boption;
    }
    
    public void setBoption(String boption) {
        this.boption = boption;
    }

    
    @Column(name="Coption", length=100)
    public String getCoption() {
        return this.coption;
    }
    
    public void setCoption(String coption) {
        this.coption = coption;
    }

    
    @Column(name="Doption", length=100)
    public String getDoption() {
        return this.doption;
    }
    
    public void setDoption(String doption) {
        this.doption = doption;
    }

    
    @Column(name="Eoption", length=100)
    public String getEoption() {
        return this.eoption;
    }
    
    public void setEoption(String eoption) {
        this.eoption = eoption;
    }

    
    @Column(name="Foption", length=100)
    public String getFoption() {
        return this.foption;
    }
    
    public void setFoption(String foption) {
        this.foption = foption;
    }

    
    @Column(name="q_type", length=20)
    public String getQType() {
        return this.QType;
    }
    
    public void setQType(String QType) {
        this.QType = QType;
    }

    
    @Column(name="q_size")
    public Integer getQSize() {
        return this.QSize;
    }
    
    public void setQSize(Integer QSize) {
        this.QSize = QSize;
    }




}
