package com.survey.entity;



import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionId generated by hbm2java
 */
@Embeddable
public class QuestionId  implements java.io.Serializable {


     private int SId;
     private int QId;

    public QuestionId() {
    }

    public QuestionId(int SId, int QId) {
       this.SId = SId;
       this.QId = QId;
    }
   


    @Column(name="s_id", nullable=false)
    public int getSId() {
        return this.SId;
    }
    
    public void setSId(int SId) {
        this.SId = SId;
    }


    @Column(name="q_id", nullable=false)
    public int getQId() {
        return this.QId;
    }
    
    public void setQId(int QId) {
        this.QId = QId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionId) ) return false;
		 QuestionId castOther = ( QuestionId ) other; 
         
		 return (this.getSId()==castOther.getSId())
 && (this.getQId()==castOther.getQId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSId();
         result = 37 * result + this.getQId();
         return result;
   }   


}


